#!/bin/sh
# ForgeCat hook wrapper (v0.2.2) — normalizes stdin then runs the real hook
# script. Do not edit this file by hand; it is regenerated on every install.
#
# Usage (from a platform's hook config):
#   command: ./<wrapper-path> <platform-id> <script-name> [args...]
#
# stdin / stdout / stderr / exit code from the user script are preserved.

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"

PLATFORM_ID="${1:-unknown}"
SCRIPT_NAME="${2:-}"
[ -z "$SCRIPT_NAME" ] && {
  echo "fc_wrap: missing script name" >&2
  exit 1
}
shift 2 2>/dev/null || true

SCRIPT_PATH="$HERE/$SCRIPT_NAME"
[ -f "$SCRIPT_PATH" ] || {
  echo "fc_wrap: script not found: $SCRIPT_PATH" >&2
  exit 1
}

INPUT="$(cat || true)"

# stdin normalize (B2): for Codex apply_patch, lift every Add/Update/Delete/
# Move-to file path out of the patch text into tool_input.file_paths (array)
# and tool_input.file_path (first, for backward-compatible single-file hooks).
#
# Security: when this is a Codex apply_patch input but jq is missing, we MUST
# fail closed. Otherwise a hook that defends by inspecting file_path would
# silently see nothing and let any patch through (the apply_patch fields are
# wrapped in tool_input.command as text, so no normalize = no visibility).
NORMALIZED="$INPUT"
IS_CODEX_APPLY_PATCH=0
if [ "$PLATFORM_ID" = "codex" ] && printf '%s' "$INPUT" | grep -q '"tool_name"[[:space:]]*:[[:space:]]*"apply_patch"'; then
  IS_CODEX_APPLY_PATCH=1
fi

HAS_JQ=0
jq --version >/dev/null 2>&1 && HAS_JQ=1

if [ "$IS_CODEX_APPLY_PATCH" -eq 1 ] && [ "$HAS_JQ" -eq 0 ]; then
  printf 'fc_wrap: jq is required for safe hook execution on Codex apply_patch input. Install jq and retry.
' >&2
  exit 2
fi

if [ "$PLATFORM_ID" = "codex" ] && [ "$HAS_JQ" -eq 1 ]; then
  PATCH_TEXT="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)"
  EXISTING_FP="$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)"
  if [ -n "$PATCH_TEXT" ]; then
    # Extract ALL file paths from patch headers. Patch grammar:
    #   *** Add File: <path>
    #   *** Update File: <path>
    #   *** Delete File: <path>
    #   *** Move to: <path>   (rename destination — follows an Update File line)
    # Security hooks rely on file_paths to see every target. A patch that
    # carries file_path but also touches more files (multi-file patch, or
    # rename via Move to:) would otherwise leave file_paths unset, letting
    # a malicious patch rename src/safe.ts → .env and bypass deny rules.
    # → Populate file_paths from the patch text regardless of whether the
    #   single file_path is already present.
    PATHS_JSON="$(printf '%s' "$PATCH_TEXT" \
      | grep -oE '\*\*\* (Add|Update|Delete) File: [^\\]+|\*\*\* Move to: [^\\]+' \
      | sed -E 's/^\*\*\* (Add|Update|Delete) File: //; s/^\*\*\* Move to: //' \
      | jq -R . \
      | jq -s . 2>/dev/null)"
    if [ -n "$PATHS_JSON" ] && [ "$PATHS_JSON" != "[]" ]; then
      # If existing file_path is set, preserve it (don't overwrite user input).
      # Otherwise, default file_path to the first patch-derived path.
      if [ -n "$EXISTING_FP" ]; then
        NORMALIZED="$(printf '%s' "$INPUT" | jq --argjson paths "$PATHS_JSON" \
          '.tool_input.file_paths = $paths')"
      else
        NORMALIZED="$(printf '%s' "$INPUT" | jq --argjson paths "$PATHS_JSON" \
          '.tool_input.file_paths = $paths
           | .tool_input.file_path = ($paths[0] // null)')"
      fi
    fi
  fi
fi

# Optional debug trace — opt in with FORGECAT_HOOK_TRACE=1
if [ "${FORGECAT_HOOK_TRACE:-}" = "1" ]; then
  LOG="${FORGECAT_HOOK_TRACE_LOG:-/tmp/forgecat-hook-trace.log}"
  {
    printf '\n=== [%s] %s at %s (pwd=%s) ===\n' \
      "$PLATFORM_ID" "$SCRIPT_NAME" "$(date -u +%H:%M:%S 2>/dev/null || echo '')" "$PWD"
    printf 'stdin (post-normalize): %s\n' "$NORMALIZED"
    printf '---\n'
  } >> "$LOG" 2>/dev/null
fi

printf '%s' "$NORMALIZED" | "$SCRIPT_PATH" "$@"
exit "$?"
