#!/usr/bin/env ruby

require "pathname"
require "yaml"

ROOT = Pathname(ENV.fetch("FORGECAT_ROOT", Pathname(__dir__).parent.expand_path.to_s)).expand_path
OUTPUT = ROOT.join("THIRD_PARTY_NOTICES.md")
EXCEPTIONS_PATH = ROOT.join("config/license-policy-exceptions.yml")
LICENSE_FILE_PATTERN = /\A(?:licen[cs]e|copying)(?:\..*)?\z/i
NOTICE_FILE_PATTERN = /\Anotice(?:\..*)?\z/i
check_only = ARGV.delete("--check")

def escape_cell(value)
  value.to_s.gsub("|", "\\|").gsub("\n", " ")
end

def original_commit(readme)
  readme[/Original commit\s*\|\s*`?([0-9a-f]{7,40})`?/i, 1] || "Not recorded"
end

def external_terms_pointer?(path)
  text = File.read(path, encoding: "UTF-8", invalid: :replace, undef: :replace)
  text.bytesize < 2_000 && text.match?(%r{https?://}) && text.match?(/governed by .* terms/i) &&
    !text.match?(/permission is hereby granted|apache license|creative commons/i)
end

exception_data = File.exist?(EXCEPTIONS_PATH) ? YAML.load_file(EXCEPTIONS_PATH) : {}
exception_rules = Hash.new { |hash, key| hash[key] = [] }
exception_data.fetch("exceptions", []).each do |row|
  exception_rules[row.fetch("profile")].concat(row.fetch("rules"))
end

rows = Dir.glob(ROOT.join("profiles/**/for-forgecat/profile.yml")).sort.map do |manifest_path|
  manifest = YAML.load_file(manifest_path) || {}
  package_dir = Pathname(manifest_path).dirname
  readme = File.read(package_dir.join("README.md"), encoding: "UTF-8")
  files = Dir.glob(package_dir.join("**/*"), File::FNM_DOTMATCH).select { |path| File.file?(path) }
  licenses = files.select { |path| File.basename(path).match?(LICENSE_FILE_PATTERN) }
  license_copies = licenses.reject { |path| external_terms_pointer?(path) }
  license_pointers = licenses - license_copies
  notices = files.select { |path| File.basename(path).match?(NOTICE_FILE_PATTERN) }

  link_files = lambda do |paths|
    paths.sort.map do |path|
      relative = Pathname(path).relative_path_from(ROOT).to_s
      "[#{File.basename(path)}](./#{relative})"
    end.join(", ")
  end

  rules = exception_rules[manifest.fetch("name")].uniq.sort
  status = rules.empty? ? "Complete" : "Review required: #{rules.join(", ")}"

  [
    "`#{manifest.fetch("name")}`",
    manifest.fetch("repository", ""),
    original_commit(readme),
    "`#{manifest.fetch("license", "")}`",
    if license_copies.any?
      link_files.call(license_copies)
    elsif license_pointers.any?
      "External terms pointer: #{link_files.call(license_pointers)}"
    else
      "Missing"
    end,
    notices.empty? ? "—" : link_files.call(notices),
    status
  ]
end

review_count = rows.count { |row| row.last.start_with?("Review required") }
license_count = rows.count do |row|
  row[4] != "Missing" && !row[4].start_with?("External terms pointer:")
end

content = <<~MARKDOWN
  # Third-Party License Notices

  This repository is licensed under Apache License 2.0 for repository-owned
  material. Individual profiles retain the license terms of their referenced
  upstream sources. The included evidence column distinguishes preserved license
  text from a pointer to external terms; a pointer is not counted as a copy.

  Generated by `ruby scripts/generate-third-party-notices.rb`. Do not edit the
  profile table manually.

  - Profiles: #{rows.size}
  - Profiles with an included license text: #{license_count}
  - Profiles with an explicit policy exception requiring review: #{review_count}

  | Profile | Upstream source | Recorded commit | License | Included license evidence | NOTICE | Policy status |
  |---|---|---|---|---|---|---|
MARKDOWN

rows.each do |row|
  content << "| #{row.map { |cell| escape_cell(cell) }.join(" | ")} |\n"
end

if check_only
  if !File.exist?(OUTPUT) || File.read(OUTPUT, encoding: "UTF-8") != content
    warn "THIRD_PARTY_NOTICES.md is stale. Run ruby scripts/generate-third-party-notices.rb"
    exit 1
  end
  puts "Third-party notice check passed (profiles=#{rows.size}, license_copies=#{license_count}, review_required=#{review_count})"
else
  File.write(OUTPUT, content)
  puts "Generated #{OUTPUT.relative_path_from(ROOT)} (profiles=#{rows.size}, license_copies=#{license_count}, review_required=#{review_count})"
end
