#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the license provenance audit table for every published profile.
#
# For each profile it records the declared license, what evidence ships with the
# profile, and whether a pinned upstream snapshot is available to match against.
# Snapshots are optional: pass --snapshots DIR (or set FORGECAT_SNAPSHOTS) to
# fill the commit column, otherwise those cells read "no-snapshot".

require "optparse"
require_relative "license_evidence"

ROOT = File.expand_path("..", __dir__)

options = { snapshots: ENV["FORGECAT_SNAPSHOTS"], out: nil }
OptionParser.new do |parser|
  parser.on("--snapshots DIR", "Directory of upstream snapshots") { |dir| options[:snapshots] = dir }
  parser.on("--out FILE", "Write the table to FILE instead of stdout") { |file| options[:out] = file }
end.parse!

def declared_license(manifest)
  manifest[/^license:[ \t]*(.+)$/, 1]&.strip || "(missing)"
end

def upstream_repository(manifest)
  manifest[/^repository:[ \t]*(.+)$/, 1]&.strip || "(missing)"
end

def repository_slug(url)
  url[%r{github\.com/([^/]+/[^/]+)}, 1] || url
end

def pinned?(url)
  !url[%r{/(?:tree|blob)/[0-9a-f]{7,40}(?:/|$)}].nil?
end

# Evidence the profile itself redistributes, in descending order of strength.
# A frontmatter `license:` line is written by the upstream author and travels
# with the exact file being redistributed, so it outranks a repository-root
# LICENSE that may not cover the copied subtree.
def shipped_evidence(profile_dir, package_dir)
  kind, path = LicenseEvidence.classify(profile_dir, package_dir)
  [kind, path ? path.delete_prefix("#{ROOT}/") : "-"]
end

# Snapshots live in github.com__<owner>__<repo>/commits/<short-sha>/, but the
# directory name is a 12-character abbreviation. The full revision is recorded as
# `archived_commit` in that directory's source.yml, and only the full one is
# usable as provenance.
def snapshot_commits(snapshots_dir, slug)
  return [] unless snapshots_dir

  owner, repo = slug.split("/")
  dir = Dir.glob(File.join(snapshots_dir, "github.com__*__*")).find do |candidate|
    File.basename(candidate).downcase == "github.com__#{owner}__#{repo}".downcase
  end
  return [] unless dir

  Dir.children(File.join(dir, "commits")).sort.map do |short|
    metadata = File.join(dir, "commits", short, "source.yml")
    next unless File.exist?(metadata)

    File.read(metadata, encoding: "UTF-8")[/^archived_commit:[ \t]*([0-9a-f]{40})\s*$/, 1]
  end.compact
rescue Errno::ENOENT
  []
end

# A profile counts as resolved only when a matcher has confirmed its files
# against a specific upstream revision and written a receipt. A pinned URL plus
# a bundled license file says the metadata looks right, which is the claim this
# audit exists to stop taking on faith.
def match_receipts(path)
  return {} unless File.exist?(path)

  File.readlines(path, chomp: true).map do |line|
    next if line.empty? || line.start_with?("#")

    profile, commit, = line.split("\t")
    [profile, commit] if profile && commit
  end.compact.to_h
end

receipts = match_receipts(File.join(ROOT, "scripts/license-matches.tsv"))

rows = Dir.glob(File.join(ROOT, "profiles/**/for-forgecat/profile.yml")).sort.map do |manifest_path|
  manifest = File.read(manifest_path, encoding: "UTF-8")
  package_dir = File.dirname(manifest_path)
  profile_dir = File.dirname(package_dir)

  repository = upstream_repository(manifest)
  slug = repository_slug(repository)
  evidence_kind, evidence_path = shipped_evidence(profile_dir, package_dir)
  commits = snapshot_commits(options[:snapshots], slug)

  profile_name = profile_dir.delete_prefix("#{ROOT}/profiles/")
  matched_commit = receipts[profile_name]

  status =
    if matched_commit && pinned?(repository) && evidence_kind != "none"
      "resolved"
    elsif matched_commit
      "matched-needs-pin-or-evidence"
    elsif commits.empty?
      "unresolved-no-snapshot"
    else
      "unresolved-needs-match"
    end

  {
    profile: profile_name,
    upstream: slug,
    matched: matched_commit || "-",
    license: declared_license(manifest),
    pinned: pinned?(repository) ? "yes" : "no",
    evidence: evidence_kind,
    evidence_path: evidence_path,
    commits: commits.empty? ? "-" : commits.join(" "),
    status: status
  }
end

lines = ["# License provenance audit",
         "",
         "Generated by `scripts/license-audit.rb`. Every published profile appears here",
         "with the license it declares, the evidence it redistributes, and whether that",
         "declaration has been matched to an exact upstream commit yet.",
         "",
         "`status` is `resolved` only when three things hold: a matcher confirmed the",
         "profile's files against a specific upstream revision and recorded it in",
         "`scripts/license-matches.tsv`, `repository` pins that revision, and the profile",
         "ships its evidence. A pinned URL on its own is a claim, not a match.",
         "`matched-needs-pin-or-evidence` has the receipt but not yet the metadata;",
         "`unresolved-needs-match` has a snapshot to match against; `unresolved-no-snapshot`",
         "needs the upstream fetched first. No unresolved state asserts that a declaration",
         "is wrong — it says nobody has checked it yet.",
         "",
         "| profile | upstream | declared license | pinned | evidence | evidence path | snapshot commits | matched commit | status |",
         "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
rows.each do |row|
  lines << "| #{row[:profile]} | #{row[:upstream]} | #{row[:license]} | #{row[:pinned]} | " \
           "#{row[:evidence]} | #{row[:evidence_path]} | #{row[:commits]} | #{row[:matched]} | #{row[:status]} |"
end

summary = rows.group_by { |row| row[:status] }.transform_values(&:length).sort.map { |k, v| "#{k}=#{v}" }
lines << ""
lines << "Total: #{rows.length} profiles (#{summary.join(', ')})."

output = "#{lines.join("\n")}\n"
if options[:out]
  File.write(options[:out], output)
  warn "wrote #{options[:out]} (#{rows.length} profiles)"
else
  print output
end
