#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the license provenance audit table for every published profile.
#
# For each profile it records the declared license, what evidence ships with the
# profile, and whether a pinned upstream snapshot is available to match against.
# Snapshots are optional: pass --snapshots DIR (or set FORGECAT_SNAPSHOTS) to
# fill the commit column, otherwise those cells read "no-snapshot".

require "optparse"

ROOT = File.expand_path("..", __dir__)

options = { snapshots: ENV["FORGECAT_SNAPSHOTS"], out: nil }
OptionParser.new do |parser|
  parser.on("--snapshots DIR", "Directory of upstream snapshots") { |dir| options[:snapshots] = dir }
  parser.on("--out FILE", "Write the table to FILE instead of stdout") { |file| options[:out] = file }
end.parse!

def declared_license(manifest)
  manifest[/^license:[ \t]*(.+)$/, 1]&.strip || "(missing)"
end

def upstream_repository(manifest)
  manifest[/^repository:[ \t]*(.+)$/, 1]&.strip || "(missing)"
end

def repository_slug(url)
  url[%r{github\.com/([^/]+/[^/]+)}, 1] || url
end

def pinned?(url)
  !url[%r{/(?:tree|blob)/[0-9a-f]{7,40}(?:/|$)}].nil?
end

# Evidence the profile itself redistributes, in descending order of strength.
# A frontmatter `license:` line is written by the upstream author and travels
# with the exact file being redistributed, so it outranks a repository-root
# LICENSE that may not cover the copied subtree.
def shipped_evidence(profile_dir, package_dir)
  license_file = Dir.glob(File.join(profile_dir, "**", "LICENSE*"), File::FNM_CASEFOLD).first
  return ["license-file", license_file.delete_prefix("#{ROOT}/")] if license_file

  frontmatter = Dir.glob(File.join(package_dir, "**", "*.md")).find do |path|
    File.foreach(path, encoding: "UTF-8").first(20).any? { |line| line.start_with?("license:") }
  end
  return ["frontmatter", frontmatter.delete_prefix("#{ROOT}/")] if frontmatter

  ["none", "-"]
end

def snapshot_commits(snapshots_dir, slug)
  return [] unless snapshots_dir

  # Snapshots are stored as github.com__<owner>__<repo>/commits/<sha>/original-repo.
  owner, repo = slug.split("/")
  dir = Dir.glob(File.join(snapshots_dir, "github.com__*__*")).find do |candidate|
    File.basename(candidate).downcase == "github.com__#{owner}__#{repo}".downcase
  end
  return [] unless dir

  Dir.children(File.join(dir, "commits")).sort
rescue Errno::ENOENT
  []
end

rows = Dir.glob(File.join(ROOT, "profiles/**/for-forgecat/profile.yml")).sort.map do |manifest_path|
  manifest = File.read(manifest_path, encoding: "UTF-8")
  package_dir = File.dirname(manifest_path)
  profile_dir = File.dirname(package_dir)

  repository = upstream_repository(manifest)
  slug = repository_slug(repository)
  evidence_kind, evidence_path = shipped_evidence(profile_dir, package_dir)
  commits = snapshot_commits(options[:snapshots], slug)

  status =
    if pinned?(repository) && evidence_kind != "none"
      "resolved"
    elsif commits.empty?
      "unresolved-no-snapshot"
    else
      "unresolved-needs-match"
    end

  {
    profile: profile_dir.delete_prefix("#{ROOT}/profiles/"),
    upstream: slug,
    license: declared_license(manifest),
    pinned: pinned?(repository) ? "yes" : "no",
    evidence: evidence_kind,
    evidence_path: evidence_path,
    commits: commits.empty? ? "-" : commits.join(" "),
    status: status
  }
end

lines = ["# License provenance audit",
         "",
         "Generated by `scripts/license-audit.rb`. Every published profile appears here",
         "with the license it declares, the evidence it redistributes, and whether that",
         "declaration has been matched to an exact upstream commit yet.",
         "",
         "`status` is `resolved` once a profile pins an exact source revision and ships",
         "its evidence. `unresolved-needs-match` means a pinned snapshot of the upstream",
         "exists and the profile's files still have to be matched against it;",
         "`unresolved-no-snapshot` means no snapshot is on hand and the upstream has to",
         "be fetched first. Neither unresolved state asserts that a declaration is wrong.",
         "",
         "| profile | upstream | declared license | pinned | evidence | evidence path | snapshot commits | status |",
         "| --- | --- | --- | --- | --- | --- | --- | --- |"]
rows.each do |row|
  lines << "| #{row[:profile]} | #{row[:upstream]} | #{row[:license]} | #{row[:pinned]} | " \
           "#{row[:evidence]} | #{row[:evidence_path]} | #{row[:commits]} | #{row[:status]} |"
end

summary = rows.group_by { |row| row[:status] }.transform_values(&:length).sort.map { |k, v| "#{k}=#{v}" }
lines << ""
lines << "Total: #{rows.length} profiles (#{summary.join(', ')})."

output = "#{lines.join("\n")}\n"
if options[:out]
  File.write(options[:out], output)
  warn "wrote #{options[:out]} (#{rows.length} profiles)"
else
  print output
end
